#BUILD AND RUN
#cd 'C:\Users\tgrant\Documents\SE Track\Backend'
#docker-compose up --build

#REMOVE VOLUMES
#docker-compose down --volumes

#PRUNE
#docker system prune

version: '2'
services:

#DJS/PERFORMANCES APP AND DATABASE

    backendnewdb:
        container_name: backendnewdb
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: tg
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: backendnewdb
        #volumes:
            #- ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - tg-network

    backendnew:
        container_name: backendnew
        build:
            dockerfile: /BackendNew/Dockerfile
        image: backendnew:latest
        ports:
            - 9090:9090
        networks:
            - tg-network

#REVIEWS APP/DATABASE

    reviewsappdb:
        container_name: reviewsappdb
        image: mongo:latest
        ports:
        - 27017:27017
        networks:
        - tg-network

    reviewsapp:
        container_name: reviewsapp
        build:
            dockerfile: /reviewsapp/Dockerfile
        image: reviewsapp:latest
        ports:
        - 9292:9292
        links:
        - reviewsappdb
        networks:
        - tg-network

networks:
    tg-network:
        driver: bridge
