#Sets target port.
server.port=9090

#Sets the datasource. For Docker-compose, the '//X:0000' must match the name of the
#service and port respectively as specified in the 'docker-compose.yaml' file. The
#final word must match the name of the database.
#spring.datasource.url=jdbc:postgresql://backendnewdb:5432/backendnewdb
spring.datasource.url=jdbc:h2:mem:backenddb
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#Specifies the login details for the database. Must match those specified in the
#'docker-compose.yaml' file.
spring.datasource.username=tg
spring.datasource.password=admin

#Instruction to initialise using 'schema.sql'
spring.sql.init.mode=never

#Sets driver
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driverClassName=org.h2.Driver

#Sets dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Updates database
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
