server.port=9090

spring.datasource.url=jdbc:postgresql://backendnewdb:5432/backendnewdb
spring.datasource.username=tg
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update