#Sets target port.
server.port=9090

#Specifies the login details for the database. Must match those specified in the
#'docker-compose.yaml' file.
spring.datasource.username=tg
spring.datasource.password=admin

#Instruction to initialise using 'schema.sql'
spring.sql.init.mode=never

#Updates database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##H2
#spring.datasource.url=jdbc:h2:mem:backenddb
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2
#spring.datasource.driverClassName=org.h2.Driver

POSTGRES
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://backendnewdb:5432/backendnewdb