-- create table if not exists DJ
--                 (ID bigint primary key not null,
--                 NAME varchar(255),
--                 GENRE varchar(255)
--                );
--
-- create table if not exists PERFORMANCE
--                 (ID bigint primary key not null,
--                 NAME varchar(255),
--                 GENRE varchar(255),
--                 DJ_ID bigint, foreign key(DJ_ID) references DJ(ID)
--                 on delete cascade
-- );
